config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
        validates :title, presence: true, length: {minimum: 5, maximum: 30}  
        validates :body, presence: true, length: {minimum: 10, maximum: 300}  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%=link_to "Rails Blog", root_path, class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
          <%= link_to 'Home', root_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Posts', posts_path, class:'nav-link'%>
        </li>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  
    <%= javascript_importmap_tags %>
  </head>
  <%= render 'layouts/navbar'%>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container mt-3 bg-success bg-opacity-25 p-3">
          <h1>About</h1>
          <p>Hey, I am Mit Donga Ruby on Rails Developer</p>
          <p>Thank you for visiting my site</p>

          <%= link_to "Back to Home", root_path, class: "btn btn-primary mt-1 mb-3" %>
</div>

app/views/pages/home.html.erb
<div class="container mt-3 bg-success bg-opacity-25 p-3">
<h1>Home</h1>
<p>Welcome to Rails Project</p>
<%= link_to "About me", about_path,class: "btn btn-primary mt-1 mb-3" %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit%>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="container bg-success bg-opacity-25 p-3">
  <h5>
    Title:
  </h5>
    <p> <%= post.title %> </p>

  <h5>
    Body:
  </h5>
  <p> <%= post.body %> </p>

</div>

app/views/posts/edit.html.erb
<div class="container">
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %>
  <%= link_to "Back to posts", posts_path %>
</div>
</div>

app/views/posts/index.html.erb
<div class="container bg-light text-dark">
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts" >
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post, class: "btn btn-primary mt-1 mb-3" %>
    </p>
  <% end %>
</div>

<%= link_to "Write New post", new_post_path, class: "btn btn-success mt-1 mb-3" %>
</div>

app/views/posts/new.html.erb
<div class="container mt-3 bg-success bg-opacity-25 p-3">
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path, class: "btn btn-primary mt-1 mb-3" %>
</div>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div class="container">
  <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-primary mt-1 mb-3" %> |
  <%= link_to "Back to posts", posts_path, class: "btn btn-primary mt-1 mb-3" %>

  <%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-danger mt-1 mb-3" %>
</div>